### ISSUE TITLE
Crash when parsing couchbase.log (Chronicle config)

### ISSUE THREAD

**Issue by stevewatanabe** [couchbaselabs/promtimer#78]
In MB-60941 promtimer crashes when parsing the couchbase.log as it finds unicode characters in the couchbase.log (see 7.2-stable_server.zip attached to the ticket).

steve.watanabe @ ~/Downloads/mb60941/7.2-stable_server/cbcollect_info_ns_1@172.23.111.134_20240226-141027 $ grep last_seen couchbase.log
     {{node,'ns_1@172.23.111.136',{"secondTestBucket",last_seen_collection_ids}},{[2,8,9],{<<"acd7cade5586ac264398f5ee0ab36202">>,647}}},
     {{node,'ns_1@172.23.111.136',{"default",last_seen_collection_ids}},{"�$Q",{<<"acd7cade5586ac264398f5ee0ab36202">>,1016}}},
     {{node,'ns_1@172.23.111.135',{"secondTestBucket",last_seen_collection_ids}},{[2,8,9],{<<"acd7cade5586ac264398f5ee0ab36202">>,648}}},
     {{node,'ns_1@172.23.111.134',{"secondTestBucket",last_seen_collection_ids}},{[2,8,9],{<<"acd7cade5586ac264398f5ee0ab36202">>,649}}},
     {{node,'ns_1@172.23.111.134',{"default",last_seen_collection_ids}},{"�$Q",{<<"acd7cade5586ac264398f5ee0ab36202">>,1017}}},
     {{node,'ns_1@172.23.111.135',{"default",last_seen_collection_ids}},{"�$Q",{<<"acd7cade5586ac264398f5ee0ab36202">>,1018}}},

Running promtimer results in

$ xpromtimer
Traceback (most recent call last):
  File "/Users/steve.watanabe/promtimer/bin/../promtimer/promtimer.py", line 441, in <module>
    main()
  File "/Users/steve.watanabe/promtimer/bin/../promtimer/promtimer.py", line 381, in main
    buckets = stats_sources[0].get_buckets()
  File "/Users/steve.watanabe/promtimer/promtimer/cbstats.py", line 201, in get_buckets
    self._config = parse_couchbase_log(self._cbcollect_dir)
  File "/Users/steve.watanabe/promtimer/promtimer/cbstats.py", line 760, in parse_couchbase_log
    config = parse_couchbase_chronicle(cbcollect_dir)
  File "/Users/steve.watanabe/promtimer/promtimer/cbstats.py", line 728, in parse_couchbase_chronicle
    for full_line in file:
  File "/Users/steve.watanabe/.pyenv/versions/3.10.13/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 2677: invalid start byte

 Based on web searching changing the open from 'r' to 'rb' gets past this but I'm not sure what side effects this has so am opening a ticket to track.

def parse_couchbase_chronicle(cbcollect_dir):
    logging.debug('parsing couchbase.log (Chronicle config)')
    bucket_list = ''
    with open(path.join(cbcollect_dir, 'couchbase.log'), 'rb') as file:

**Comment by dave-finlay** [comment]
Hi Steve - Vesko just pushed a PR on that and I merged earlier this morning. https://github.com/couchbaselabs/promtimer/pull/76. So should be resolved.
